server:
  port: 8082
spring:
  application:
    name: adminClient1
  boot:
    admin:
      client:
        url: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"